### ISSUE TITLE
[Product] Bug - If not images then still show Product Page

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#1304]
On the LSIG Product Page, in EDS there is a block called product-hero and in the imageSlider there is a function to build the images.  However, if no images are assigned to the product in PIM then the page completely breaks and this error is in the console:
 
failed to load module for product-hero TypeError: Cannot read properties of undefined (reading '0')
    at imageSlider (product-hero.js:40:90)
    at decorate (product-hero.js:173:34)
    at async lib-franklin.js:1:10991
 
 
The API call to get the data is here:  https://lifesciences.danaher.com/us/en/product-data/?product=valita-titer and in the response, in the ‘raw’ data the images are listed.  David has added the default image to the list if blank.
 
Please don’t change the API call, but in the product-hero, can we code it so that if it doesn’t find any images in the call then it will still show the page, but the images will be the default or blank.
 
This page might be fixed in time for when you see this, but I can ask David/Praveen to reproduce this on Staging if needed:
 
https://lifesciences.danaher.com/us/en/products/family/valita-titer.html

**Comment by Raja-danaher** [comment]
issue has been fixed.
